server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: UmaRamesh@1992
    url: "jdbc:mysql://localhost:3306/world"
    username: demo
  jpa:
    database: mysql
    show-sql: true
