CREATE TABLE SITES (
   SITE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,PRIMARY KEY (SITE_ID),
   SITE_NAME VARCHAR(30) NOT NULL,
   SITE_OWNER VARCHAR(30)
);

INSERT INTO SITES (SITE_NAME,SITE_OWNER) VALUES('SITE_2','SITE_OWNER_2');